# -*- coding: utf-8 -*-
"""Muhammad Roshaan Idrees_56177_AI_Lab12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yJfq3lqLDBrkxbOtZ_Em76HGGdhpGFX

**Muhammad Roshaan Idrees**

---


**56177**

# Use different dataset [NLP/Image], change parameters and analyze effects of changing parameter on output.
"""

# Load packages
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.svm import SVC

# Load the datasets
digits = load_digits()
X = digits.data[:, :2]
y = digits.target

# Build the model
svm = SVC(kernel="rbf", gamma=0.5, C=1.0)
# Train the model
svm.fit(X, y)

# Plot Decision Boundary
DecisionBoundaryDisplay.from_estimator(
    svm,
    X,
    response_method="predict",
    cmap=plt.cm.Spectral,
    alpha=0.8,
    xlabel="Feature 1",
    ylabel="Feature 2",
)

# Scatter plot
plt.scatter(X[:, 0], X[:, 1],
   c=y,
   s=20, edgecolors="k")
plt.show()