# -*- coding: utf-8 -*-
"""Muhammad Roshaan Idrees_56177_AI_Lab11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiZJgA7d0JfvWwqKb2SXm5peBdj98rCZ

**Muhammad Roshaan Idrees**

---


**56177**

# Implement Naïve Bayes Classifier:
• Implement Naïve Bayes Classifier with different dataset and parameters

• Implement Naïve Bayes Classifier on different dataset (multiclass)

• Display model Evaluation

Diabetes Dataset.....
"""

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Load dataset
diabetes = load_diabetes()
X, y = diabetes.data, (diabetes.target > diabetes.target.mean()).astype(int)
# Convert regression target into binary classification (above/below mean)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Build and train model
model = GaussianNB(var_smoothing=1e-9)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("Diabetes Dataset → Accuracy:", accuracy_score(y_test, y_pred))
print("Diabetes Dataset → F1 Score:", f1_score(y_test, y_pred, average="weighted"))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Below Avg", "Above Avg"])
disp.plot()
plt.show()

"""Digits Dataset.....

"""

from sklearn.datasets import load_digits

digits = load_digits()
X, y = digits.data, digits.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Digits Dataset → Accuracy:", accuracy_score(y_test, y_pred))
print("Digits Dataset → F1 Score:", f1_score(y_test, y_pred, average="weighted"))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=digits.target_names)
disp.plot()
plt.show()

"""Model Evaluation....."""

from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Iris Dataset → Accuracy:", accuracy_score(y_test, y_pred))
print("Iris Dataset → F1 Score:", f1_score(y_test, y_pred, average="weighted"))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=iris.target_names)
disp.plot()
plt.show()