# -*- coding: utf-8 -*-
"""Muhammad Roshaan Idrees_56177_AI_Lab08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxu3Q2eB8frmZFrodYzYxAYpmHu8amug

**Muhammad Roshaan Idrees**

---


**56177**

# **1: Create Dictionary and Bar Graph of Fruit Prices.**
"""

import pandas as pd
import matplotlib.pyplot as plt

# Create dictionary of fruit prices
data = {
    'Fruits': ['Mango', 'Apple', 'Banana'],
    'Rawalpindi': [80, 40, 60],
    'Lahore': [100, 90, 30],
    'Islamabad': [90, 50, 100]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Set 'Fruits' as index for plotting
df.set_index('Fruits', inplace=True)

# Plot bar graph
df.plot(kind='bar')
plt.title('Fruit Prices in Different Cities')
plt.ylabel('Price (PKR)')
plt.xlabel('Fruit')
plt.grid(True)
plt.show()

"""# **2: Load Dataset and Explore It.**"""

# Display first few rows
print("First few rows:\n", df.head())

# Summary statistics
print("\nSummary statistics:\n", df.describe())

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

"""# **3: Perform Data Analysis**"""

# Calculate average price for each fruit
df['Average'] = df.mean(axis=1)
print("\nAverage price for each fruit:\n", df['Average'])

# Highest and lowest price for each fruit
df['Max'] = df.max(axis=1)
df['Min'] = df.min(axis=1)
print("\nHighest price for each fruit:\n", df['Max'])
print("\nLowest price for each fruit:\n", df['Min'])

# Overall average price across all cities and fruits
overall_avg = df[['Rawalpindi', 'Lahore', 'Islamabad']].values.mean()
print("\nOverall average price:", overall_avg)

"""# **3: Visualize the Data**

# **Histogram of Fruit Prices**
"""

# Histogram of all prices
df[['Rawalpindi', 'Lahore', 'Islamabad']].plot(kind='hist', bins=5, alpha=0.7)
plt.title('Distribution of Fruit Prices')
plt.xlabel('Price (PKR)')
plt.grid(True)
plt.show()

"""# **Bar Plot of Average Prices**"""

# Bar plot of average prices
df['Average'].plot(kind='bar', color='orange')
plt.title('Average Fruit Prices Across Cities')
plt.ylabel('Average Price (PKR)')
plt.xlabel('Fruit')
plt.grid(True)
plt.show()

"""# **Pie Chart of Average Prices**"""

# Pie chart of average prices
df['Average'].plot(kind='pie', autopct='%1.1f%%', figsize=(6, 6))
plt.title('Average Fruit Price Distribution')
plt.ylabel('')
plt.show()

"""# **4: Explore the dataset**"""

# Display first few rows
print("First few rows:\n", df.head())

# Summary statistics
print("\nSummary statistics:\n", df.describe())

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

"""# **5: Perform Data Analysis**"""

# Calculate overall average price
overall_avg = df[['Rawalpindi', 'Lahore', 'Islamabad']].values.mean()
print("\nOverall average price:", overall_avg)

# Highest and lowest price for each fruit
df['Max'] = df[['Rawalpindi', 'Lahore', 'Islamabad']].max(axis=1)
df['Min'] = df[['Rawalpindi', 'Lahore', 'Islamabad']].min(axis=1)
print("\nHighest price per fruit:\n", df['Max'])
print("\nLowest price per fruit:\n", df['Min'])

"""# **6: Write a Pandas program to insert a new column in existing DataFrame.**"""

import pandas as pd;
# Insert new column: Price Range
df['Price_Range'] = df['Max'] - df['Min']
print("\nDataFrame with new column:\n", df)