# -*- coding: utf-8 -*-
"""Muhammad Roshaan Idrees _ 56177 _ AI Lab_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDkdEuHrjuESRDJg_7Xv5WzrsnwaypJv

**Muhammad Roshaan Idrees**
**56177**

1. Create Numpy array, split into 3 arrays then calculate sum of all arrays numbers.
"""

import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

split_arrays = np.array_split(original_array, 3)

total_sum = np.sum(original_array)

print("Original Array:", original_array)
print("Split Arrays:", split_arrays)
print("Sum of all numbers:", total_sum)

"""2. Create a NumPy array to extract all numbers greater than 5 and less than 15."""

arr = np.array([1, 3, 7, 10, 14, 5, 18, 2, 9, 12])

extracted_numbers = arr[(arr > 5) & (arr < 15)]

print("Original Array:", arr)
print("Numbers > 5 and < 15:", extracted_numbers)

"""3. Create two sets (at least one set through constructor)

set1 = {Even numbers (0-10)}

set2 = {Positive integers (1-10)}

a) Remove second and fifth element of set2

b) set3 = {intersection of set2 and set1}

"""

set1 = {0, 2, 4, 6, 8, 10}

set2 = set(range(1, 11))

print("Original set2:", set2)

# --- a ---

list_set2 = list(set2)
del list_set2[4]
del list_set2[1]
set2 = set(list_set2)

print("set2 after removal:", set2)

# --- b ---

set3 = set2.intersection(set1)

print("set1 (Evens 0-10):", set1)
print("set2 (Positives 1-10):", set2)
print("Intersection set3:", set3)

"""4. Create a dictionary named “students”. Store 5 different students record into dictionary.
For key used sapId of the student. Student record should contain: sapid, name, age and
Semester (Six). Update the Semester (Six) to Semester (Seven).
"""

students = {
    50001: {"sapId": 50001, "name": "Ali", "age": 20, "semester": "Six"},
    50002: {"sapId": 50002, "name": "Arbaz", "age": 21, "semester": "Six"},
    50003: {"sapId": 50003, "name": "Ahmed", "age": 22, "semester": "Six"},
    50004: {"sapId": 50004, "name": "Faizan", "age": 19, "semester": "Six"},
    50005: {"sapId": 50005, "name": "Zain", "age": 20, "semester": "Six"}
}

print("Students before update:")
for sap_id, details in students.items():
    print(f"SAP ID: {sap_id}, Details: {details}")

for sap_id in students:
    students[sap_id]["semester"] = "Seven"

print("\nStudents after update:")
for sap_id, details in students.items():
    print(f"SAP ID: {sap_id}, Details: {details}")