# -*- coding: utf-8 -*-
"""Muhammad Roshaan Idrees_56177_AI_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwlWLcYUrfVWKte0SQI-dJQWsaUULOgX

**Muhammad Roshaan Idrees**          
  **56177**

Arihmetic Operators
"""

print("Sum of Numbers: ", 2+3)

print("Difference of Numbers: ", 3-2)

print("Multiplication of Numbers: ", 2*3)

print("Division of Numbers: ", 3/2)

print("Modulus of Numbers: ", 3%2)

"""Assignment Operators"""

x=5;
x+=3;
print("value of x: ", x)

x=5;
x-=3;
print("value of x: ", x)

x=5;
x*=3;
print("value of x: ", x)

x=5;
 x/=3;
 print("value of x: ", x)

x=5;
x%=3;
print("value of x: ", x)

"""Comparison Operators"""

print(2==3)

print(2!=3)

print(2>3)

print(2<3)

print(2>=3)

print(2<=3)

"""Logical Operators"""

print(2<5 and 2<10)

print(2<5 or 2<10)

print(not(2<5))